server:
  port: 9001

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: HSQL
    
security:
  user:
    password: password
    
logging:
  level:
    org.springframework.security: DEBUG
    com.comcast.sparrow.web: DEBUG
