server:
  port: 9000

security:
  user:
    password: password

zuul:
  routes:
    sparrow-catalog: /catalog/**
    sparrow-reviews: /reviews/**
    sparrow-recommendations: /recommendations/**
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user

spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user


logging:
  level:
    org.springframework.security: INFO
    org.springframework.cloud.netflix: INFO
    com.netflix.zuul: INFO
    io.springbox.apigateway: DEBUG
