server:
  port: 7779
spring:
  oauth2:
    resource:
      userInfoUri: http://sparrow-auth-server.cfapps.pez.pivotal.io/uaa/user
logging:
  logging:
    org.springframework.web: DEBUG
    io.sparrow.recommendations: DEBUG